name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install project dependencies
        run: pnpm install

      - name: Run Vite build (development)
        run: pnpm run build:css

      - name: Run Vite build (production minified)
        run: pnpm run build:css:min

      - name: Create release package
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: NLB Stylesheets (${{ github.ref }})
          draft: false
          prerelease: false
          
      - name: Upload ebok.min.css asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/css/ebok.min.css
          asset_name: ebok.min.css
          asset_content_type: text/css
          
      - name: Upload epub.min.css asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/css/epub.min.css
          asset_name: epub.min.css
          asset_content_type: text/css
          
      - name: Upload html.min.css asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/css/html.min.css
          asset_name: html.min.css
          asset_content_type: text/css
          
      - name: Upload ncc.min.css asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/css/ncc.min.css
          asset_name: ncc.min.css
          asset_content_type: text/css
          
      - name: Upload nettleserbok.min.css asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/css/nettleserbok.min.css
          asset_name: nettleserbok.min.css
          asset_content_type: text/css
          
      - name: Upload rb_smil_emulator.js asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/js/rb_smil_emulator.js
          asset_name: rb_smil_emulator.js
          asset_content_type: text/javascript
